import streamlit as st
import os
import io
import time
import base64
from PIL import Image
import numpy as np

# ── Page config (must be first Streamlit call) ──────────────────────────────
st.set_page_config(
    page_title="MedClear – Healthcare AI Assistant",
    page_icon="🏥",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ── Inject custom CSS ────────────────────────────────────────────────────────
with open("style.css") as f:
    st.markdown(f"<style>{f.read()}</style>", unsafe_allow_html=True)

# ── Lazy imports with user-friendly error messages ──────────────────────────
@st.cache_resource(show_spinner=False)
def load_ocr():
    import easyocr
    return easyocr.Reader(["en"], gpu=False)

def get_groq_client():
    from groq import Groq
    api_key = st.session_state.get("groq_api_key") or os.environ.get("GROQ_API_KEY", "")
    if not api_key:
        return None
    return Groq(api_key=api_key)

# ── Helpers ──────────────────────────────────────────────────────────────────
def extract_text_from_pdf(uploaded_file) -> str:
    import pypdf
    reader = pypdf.PdfReader(uploaded_file)
    text = ""
    for page in reader.pages:
        text += page.extract_text() or ""
    return text.strip()

def extract_text_from_image(image_bytes: bytes) -> str:
    reader = load_ocr()
    img_array = np.array(Image.open(io.BytesIO(image_bytes)))
    results = reader.readtext(img_array, detail=0)
    return "\n".join(results)

LANGUAGE_NAMES = {
    "English": "English",
    "Hindi": "Hindi (हिंदी)",
    "Kannada": "Kannada (ಕನ್ನಡ)",
    "Tamil": "Tamil (தமிழ்)",
    "Telugu": "Telugu (తెలుగు)",
}

LANGUAGE_PROMPTS = {
    "English": "English",
    "Hindi": "Hindi",
    "Kannada": "Kannada",
    "Tamil": "Tamil",
    "Telugu": "Telugu",
}

SUMMARY_SYSTEM_PROMPT = """You are MedClear, a compassionate medical communication AI.
Your job is to convert complex medical/clinical text into easy-to-understand patient-friendly summaries.

RULES:
- Use ONLY information from the provided document. Do NOT invent, assume, or hallucinate any medical information.
- If a section has no relevant data in the document, write "Not mentioned in the document."
- Always include the Safety Note.
- Respond in {language}.

OUTPUT FORMAT (use exactly these section headers with emoji):

🩺 DIAGNOSIS
[Simple, plain-language explanation of the condition(s)]

💊 MEDICATIONS
For each medication found:
- Name: [medicine name]
- Purpose: [what it treats]
- Instructions: [dosage/timing/special notes]

📅 FOLLOW-UP CARE
- Appointments: [dates/specialists]
- Tests: [any required tests]
- Monitoring: [what to track at home]

⚠️ WARNING SIGNS
[Symptoms that require immediate medical attention]

🏠 HOME CARE INSTRUCTIONS
- Daily care: [guidance]
- Activity: [recommendations]
- Recovery tips: [advice]

🔒 SAFETY NOTE
This summary was generated by AI and is based solely on the provided document. It must be reviewed by a qualified healthcare professional before being shared with the patient.
"""

CHAT_SYSTEM_PROMPT = """You are MedClear, a helpful medical assistant.
You have access to the following medical document:

---
{document}
---

RULES:
- Answer ONLY using information from the above document.
- If the answer is not in the document, say: "This information is not available in the provided document."
- Be clear, concise, and compassionate.
- Respond in {language}.
- Do NOT give generic medical advice beyond what's in the document.
"""

def generate_summary(text: str, language: str) -> str:
    client = get_groq_client()
    if not client:
        return "⚠️ Please enter your Groq API key in the sidebar to generate summaries."
    system = SUMMARY_SYSTEM_PROMPT.replace("{language}", LANGUAGE_PROMPTS[language])
    response = client.chat.completions.create(
        model="llama-3.1-8b-instant",
        messages=[
            {"role": "system", "content": system},
            {"role": "user", "content": f"Please summarize this medical document:\n\n{text}"},
        ],
        temperature=0.3,
        max_tokens=2048,
    )
    return response.choices[0].message.content

def chat_with_document(messages: list, document: str, language: str) -> str:
    client = get_groq_client()
    if not client:
        return "⚠️ Please enter your Groq API key in the sidebar."
    system = CHAT_SYSTEM_PROMPT.replace("{document}", document).replace("{language}", LANGUAGE_PROMPTS[language])
    groq_messages = [{"role": "system", "content": system}] + messages
    response = client.chat.completions.create(
        model="llama-3.1-8b-instant",
        messages=groq_messages,
        temperature=0.3,
        max_tokens=1024,
    )
    return response.choices[0].message.content

def generate_pdf_report(summary: str, language: str) -> bytes:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import cm
    from reportlab.lib import colors
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
    from reportlab.lib.enums import TA_CENTER, TA_LEFT

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4,
                            leftMargin=2*cm, rightMargin=2*cm,
                            topMargin=2*cm, bottomMargin=2*cm)

    styles = getSampleStyleSheet()
    teal = colors.HexColor("#0d9488")
    dark = colors.HexColor("#0f172a")

    title_style = ParagraphStyle("title", parent=styles["Title"],
                                  fontSize=22, textColor=teal, spaceAfter=4,
                                  alignment=TA_CENTER, fontName="Helvetica-Bold")
    sub_style = ParagraphStyle("sub", parent=styles["Normal"],
                                fontSize=10, textColor=colors.grey,
                                alignment=TA_CENTER, spaceAfter=16)
    body_style = ParagraphStyle("body", parent=styles["Normal"],
                                 fontSize=11, leading=16, textColor=dark,
                                 spaceAfter=8)

    story = []
    story.append(Paragraph("🏥 MedClear Patient Summary", title_style))
    story.append(Paragraph(f"Language: {LANGUAGE_NAMES[language]}  |  Generated by MedClear AI", sub_style))
    story.append(HRFlowable(width="100%", thickness=1, color=teal, spaceAfter=16))

    for line in summary.split("\n"):
        line = line.strip()
        if not line:
            story.append(Spacer(1, 8))
        elif line.startswith(("🩺", "💊", "📅", "⚠️", "🏠", "🔒")):
            story.append(Spacer(1, 10))
            hdr = ParagraphStyle("hdr", parent=styles["Heading2"],
                                  fontSize=13, textColor=teal, fontName="Helvetica-Bold",
                                  spaceAfter=6)
            story.append(Paragraph(line, hdr))
        else:
            story.append(Paragraph(line.replace("&", "&amp;").replace("<", "&lt;"), body_style))

    story.append(Spacer(1, 20))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.grey))
    story.append(Paragraph("This document is AI-generated. Please consult a healthcare professional.", sub_style))

    doc.build(story)
    return buf.getvalue()

# ── Session state defaults ───────────────────────────────────────────────────
for key, default in {
    "extracted_text": "",
    "summary": "",
    "chat_history": [],
    "language": "English",
    "camera_active": False,
    "source_label": "",
}.items():
    if key not in st.session_state:
        st.session_state[key] = default

# ════════════════════════════════════════════════════════════════════════════
#  SIDEBAR
# ════════════════════════════════════════════════════════════════════════════
with st.sidebar:
    st.markdown('<div class="sidebar-logo">🏥 MedClear</div>', unsafe_allow_html=True)
    st.markdown('<p class="sidebar-tagline">AI-Powered Medical Communication</p>', unsafe_allow_html=True)
    st.divider()

    # API Key
    st.markdown("### 🔑 Groq API Key")
    api_key_input = st.text_input("Enter your key", type="password",
                                   value=st.session_state.get("groq_api_key", ""),
                                   placeholder="gsk_…", label_visibility="collapsed")
    if api_key_input:
        st.session_state["groq_api_key"] = api_key_input
        st.success("✅ API key saved", icon="🔐")
    else:
        st.info("Enter Groq API key to enable AI features.")

    st.divider()

    # Language
    st.markdown("### 🌐 Output Language")
    lang = st.selectbox("Language", list(LANGUAGE_NAMES.keys()),
                         index=list(LANGUAGE_NAMES.keys()).index(st.session_state["language"]),
                         label_visibility="collapsed")
    st.session_state["language"] = lang
    st.caption(f"Summaries will be in **{LANGUAGE_NAMES[lang]}**")

    st.divider()

    # Safety Panel
    st.markdown("""
    <div class="safety-panel">
      <div class="safety-title">🛡️ Safety Guidelines</div>
      <ul class="safety-list">
        <li>AI uses only your uploaded document</li>
        <li>No medical information is invented</li>
        <li>Always consult a professional</li>
        <li>Not a substitute for clinical advice</li>
      </ul>
    </div>
    """, unsafe_allow_html=True)

    st.divider()
    st.caption("MedClear v1.0 · Powered by Groq + Llama 3.1")

# ════════════════════════════════════════════════════════════════════════════
#  MAIN CONTENT
# ════════════════════════════════════════════════════════════════════════════
st.markdown('<h1 class="main-title">🏥 MedClear Healthcare AI Assistant</h1>', unsafe_allow_html=True)
st.markdown('<p class="main-subtitle">Transform complex medical reports into clear, patient-friendly summaries</p>', unsafe_allow_html=True)

# ── TAB LAYOUT ───────────────────────────────────────────────────────────────
tab_input, tab_summary, tab_chat = st.tabs(["📂 Upload & Extract", "📋 AI Summary", "💬 Ask MedClear"])

# ═══════════ TAB 1: INPUT ════════════════════════════════════════════════════
with tab_input:
    st.markdown("### Choose your input method")

    col1, col2 = st.columns([1, 1], gap="large")

    # ── Left: Upload / Camera ─────────────────────────────────────────────
    with col1:
        st.markdown('<div class="card">', unsafe_allow_html=True)
        st.markdown("#### 📁 Upload Document")

        input_method = st.radio("Input method", ["PDF Report", "Image File", "Camera Capture"],
                                 horizontal=True, label_visibility="collapsed")

        if input_method == "PDF Report":
            uploaded_pdf = st.file_uploader("Upload PDF", type=["pdf"],
                                             label_visibility="collapsed",
                                             help="Discharge summaries, prescriptions, lab reports…")
            if uploaded_pdf:
                with st.spinner("📄 Reading PDF…"):
                    text = extract_text_from_pdf(uploaded_pdf)
                if text:
                    st.session_state["extracted_text"] = text
                    st.session_state["source_label"] = uploaded_pdf.name
                    st.success(f"✅ Extracted {len(text.split())} words from **{uploaded_pdf.name}**")
                else:
                    st.warning("⚠️ No text found – the PDF may be scanned. Try uploading as image.")

        elif input_method == "Image File":
            uploaded_img = st.file_uploader("Upload Image", type=["jpg", "jpeg", "png"],
                                             label_visibility="collapsed")
            if uploaded_img:
                img_bytes = uploaded_img.read()
                st.image(img_bytes, caption="Uploaded image", use_container_width=True)
                with st.spinner("🔍 Running OCR…"):
                    text = extract_text_from_image(img_bytes)
                if text:
                    st.session_state["extracted_text"] = text
                    st.session_state["source_label"] = uploaded_img.name
                    st.success(f"✅ Extracted {len(text.split())} words via OCR")
                else:
                    st.warning("⚠️ Could not extract text. Try a clearer image.")

        elif input_method == "Camera Capture":
            cam_col1, cam_col2 = st.columns(2)
            with cam_col1:
                if st.button("📷 Turn Camera ON" if not st.session_state["camera_active"] else "⏹ Turn Camera OFF",
                              use_container_width=True):
                    st.session_state["camera_active"] = not st.session_state["camera_active"]

            if st.session_state["camera_active"]:
                camera_image = st.camera_input("Point at document and capture",
                                                label_visibility="collapsed")
                if camera_image:
                    img_bytes = camera_image.getvalue()
                    with st.spinner("🔍 Running OCR on captured image…"):
                        text = extract_text_from_image(img_bytes)
                    if text:
                        st.session_state["extracted_text"] = text
                        st.session_state["source_label"] = "Camera Capture"
                        st.success(f"✅ Extracted {len(text.split())} words from camera")
                        st.session_state["camera_active"] = False
                        st.rerun()
                    else:
                        st.warning("⚠️ No text detected. Try better lighting.")
            else:
                st.info("Click **Turn Camera ON** to activate your device camera.")

        st.markdown('</div>', unsafe_allow_html=True)

    # ── Right: Manual text / Preview ─────────────────────────────────────
    with col2:
        st.markdown('<div class="card">', unsafe_allow_html=True)
        st.markdown("#### ✏️ Manual Text Input")
        manual_text = st.text_area("Paste or type medical text here",
                                    height=220,
                                    placeholder="Paste discharge notes, prescriptions, or any medical text…",
                                    label_visibility="collapsed")
        if st.button("✅ Use This Text", use_container_width=True, disabled=not manual_text.strip()):
            st.session_state["extracted_text"] = manual_text.strip()
            st.session_state["source_label"] = "Manual Input"
            st.success("✅ Text ready for processing")
        st.markdown('</div>', unsafe_allow_html=True)

    # ── Extracted text preview ────────────────────────────────────────────
    if st.session_state["extracted_text"]:
        st.divider()
        with st.expander(f"👁 Preview extracted text  ({len(st.session_state['extracted_text'].split())} words)", expanded=False):
            st.text_area("Extracted content", st.session_state["extracted_text"],
                         height=200, label_visibility="collapsed", disabled=True)

        # Generate button
        st.markdown("---")
        gcol1, gcol2, gcol3 = st.columns([1, 2, 1])
        with gcol2:
            if st.button("🚀 Generate Patient-Friendly Summary", use_container_width=True, type="primary"):
                if not st.session_state.get("groq_api_key") and not os.environ.get("GROQ_API_KEY"):
                    st.error("⚠️ Please enter your Groq API key in the sidebar first.")
                else:
                    with st.spinner("🧠 MedClear is analysing the document…"):
                        progress = st.progress(0)
                        for i in range(0, 80, 10):
                            time.sleep(0.1)
                            progress.progress(i)
                        summary = generate_summary(
                            st.session_state["extracted_text"],
                            st.session_state["language"]
                        )
                        progress.progress(100)
                        time.sleep(0.2)
                        progress.empty()
                    st.session_state["summary"] = summary
                    st.session_state["chat_history"] = []  # reset chat
                    st.success("✅ Summary generated! Switch to the **AI Summary** tab.")

# ═══════════ TAB 2: SUMMARY ══════════════════════════════════════════════════
with tab_summary:
    if not st.session_state["summary"]:
        st.markdown("""
        <div class="empty-state">
          <div class="empty-icon">📋</div>
          <h3>No summary yet</h3>
          <p>Upload a document in the <strong>Upload & Extract</strong> tab and click <em>Generate Summary</em>.</p>
        </div>
        """, unsafe_allow_html=True)
    else:
        # Meta bar
        meta_col1, meta_col2, meta_col3 = st.columns(3)
        with meta_col1:
            st.markdown(f'<div class="meta-chip">📄 Source: {st.session_state["source_label"]}</div>',
                        unsafe_allow_html=True)
        with meta_col2:
            st.markdown(f'<div class="meta-chip">🌐 Language: {LANGUAGE_NAMES[st.session_state["language"]]}</div>',
                        unsafe_allow_html=True)
        with meta_col3:
            st.markdown('<div class="meta-chip confidence">🟢 Confidence: High</div>',
                        unsafe_allow_html=True)

        st.markdown("---")

        # Summary display
        st.markdown('<div class="summary-box">', unsafe_allow_html=True)
        st.markdown(st.session_state["summary"])
        st.markdown('</div>', unsafe_allow_html=True)

        st.markdown("---")

        # Download PDF
        dcol1, dcol2, dcol3 = st.columns([1, 2, 1])
        with dcol2:
            with st.spinner("📄 Preparing PDF…"):
                pdf_bytes = generate_pdf_report(
                    st.session_state["summary"],
                    st.session_state["language"]
                )
            st.download_button(
                label="⬇️ Download Summary as PDF",
                data=pdf_bytes,
                file_name=f"medclear_summary_{st.session_state['language'].lower()}.pdf",
                mime="application/pdf",
                use_container_width=True,
                type="primary",
            )

        # AI warning
        st.markdown("""
        <div class="ai-warning">
          ⚠️ <strong>AI-Generated Content:</strong> This summary was created by an AI model and is intended to assist — not replace — professional medical advice.
          Always have a qualified healthcare professional review this before sharing with a patient.
        </div>
        """, unsafe_allow_html=True)

# ═══════════ TAB 3: CHAT ═════════════════════════════════════════════════════
with tab_chat:
    if not st.session_state["extracted_text"]:
        st.markdown("""
        <div class="empty-state">
          <div class="empty-icon">💬</div>
          <h3>No document loaded</h3>
          <p>Upload a document first to start asking questions.</p>
        </div>
        """, unsafe_allow_html=True)
    else:
        st.markdown("### 💬 Ask Questions About Your Medical Document")
        st.caption("MedClear answers using only the information in your uploaded document.")

        # Quick question chips
        st.markdown("**Quick questions:**")
        q_cols = st.columns(2)
        quick_qs = [
            "What medicines should I take?",
            "What precautions should I follow?",
            "What symptoms should I watch for?",
            "When should I visit the doctor again?",
        ]
        for i, q in enumerate(quick_qs):
            with q_cols[i % 2]:
                if st.button(q, key=f"qb_{i}", use_container_width=True):
                    st.session_state["chat_history"].append({"role": "user", "content": q})
                    with st.spinner("🤔 MedClear is thinking…"):
                        reply = chat_with_document(
                            st.session_state["chat_history"],
                            st.session_state["extracted_text"],
                            st.session_state["language"],
                        )
                    st.session_state["chat_history"].append({"role": "assistant", "content": reply})
                    st.rerun()

        st.divider()

        # Chat history
        if st.session_state["chat_history"]:
            for msg in st.session_state["chat_history"]:
                if msg["role"] == "user":
                    st.markdown(f'<div class="chat-user"><strong>You:</strong> {msg["content"]}</div>',
                                unsafe_allow_html=True)
                else:
                    st.markdown(f'<div class="chat-bot"><strong>🏥 MedClear:</strong><br>{msg["content"]}</div>',
                                unsafe_allow_html=True)

        # Custom input
        user_q = st.chat_input("Ask a question about the document…")
        if user_q:
            st.session_state["chat_history"].append({"role": "user", "content": user_q})
            with st.spinner("🤔 MedClear is thinking…"):
                reply = chat_with_document(
                    st.session_state["chat_history"],
                    st.session_state["extracted_text"],
                    st.session_state["language"],
                )
            st.session_state["chat_history"].append({"role": "assistant", "content": reply})
            st.rerun()

        if st.session_state["chat_history"]:
            if st.button("🗑 Clear Chat", use_container_width=False):
                st.session_state["chat_history"] = []
                st.rerun()
